### ISSUE TITLE
connection issues: FATAL: database "user" does not exist

### ISSUE THREAD

**Issue by lukehinds** [Dzordzu/rust-apache-age#1]
Hey @Dzordzu 

Thanks for your work on the driver. I have the following issue, but I don't think its related to your code, but I figured its worth seeing if you have some ideas

I am pulling up age using a docker-compose file and the official image:

```yaml
version: "3.3"
services:
  db:
    image: apache/age
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  ```

The server is running:

```
sudo netstat -vanp tcp |grep 5432
Password:
tcp46      0      0  *.5432                 *.*                    LISTEN       131072  131072  82035      0 00100 00000006 00000000008bf447 00000000 00000800      1      0 000001
```

I can connect with the credentials:

```bash
psql --host=localhost --username=user --dbname=db
Password for user user: 
psql (14.5 (Homebrew), server 11.13 (Debian 11.13-1.pgdg100+1))
Type "help" for help.

db=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 user      | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

Yet when I try to connect using this crate, I get 

```
Error: db error: FATAL: database "user" does not exist

Caused by:
    FATAL: database "user" does not exist
```

My code:

```rust
use anyhow::Result;
use apache_age::{NoTls};
use apache_age::tokio::{AgeClient, Client};

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let (mut client, _) = Client::connect_age(
        "host=0.0.0.0 user=user password=pass port=5432",
        NoTls,
    )
    .await?;
    
    client.create_graph("sscg").await?;

     Ok(())
}
```

Any ideas? I cannot figure this out myself.
